version: "3"

tasks:
  run:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - g++ -std=c++20 -o ./main ./main.cpp
      - defer: rm ./main
      - ./main
    aliases:
      - r

  new:
    dir: "{{.TASKFILE_DIR}}"
    requires:
      vars:
        - Y
        - D
    cmds:
      - mkdir -p 20{{.Y}}/day{{.D}}
      - touch 20{{.Y}}/day{{.D}}/{input.txt,example.txt,main.cpp}
